name: terraform
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
   
    defaults:
      run:
        shell: bash 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest

    - name: Login to Azure
      run: az login --service-principal -u ${{ secrets.APPLICATION_CLIENT_ID }} -p ${{ secrets.SECERET_ID }} --tenant ${{ secrets.DIRECTORY_TENANT_ID }}    

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan 

    - name: Terraform Apply
      run: terraform apply -auto-approve 